In [3]:
#Ex1
import numpy as np
new_array=np.array([[1,2],[3,4],[5,5]])
new_list=new_array.tolist()
print(new_list)

[[1, 2], [3, 4], [5, 5]]


In [14]:
#Ex2
import numpy as np
a=np.random.randint(1,9,size=(3,3))
i=0
c=-1
sum=0
while i<len(a):
  sum+=a[i,i]
  sum+=a[c,i]
  i+=1
  c+=-1
print(a,'\n',"sum of the diagonal elements is:",sum)

[[1 7 7]
 [1 2 2]
 [5 2 6]] 
 sum of the diagonal elements is: 23


In [18]:
#Ex3
import numpy as np
x=np.random.randint(0,9)
a=np.array([[1,2],[3,5]])
i=0
result=list()
print('x=',x)
while i<len(a):
  b=0
  while b<len(a[i]):
    if a[i,b]>=x:
      result.append(a[i,b])
    b=b+1
  i+=1
print("the numbers higher than x are:",result)

x= 0
the numbers higher than x are: [1, 2, 3, 5]


In [23]:
#Ex4
import numpy as np
a=np.random.randint(0,9,size=(2,4))
b=np.random.randint(0,9,size=(2,4))
c=a+b
print("array 1:",a,'\n\n',"array 2:",b,'\n\n',"sum:",c)

array 1: [[1 1 4 5]
 [6 8 4 2]] 

 array 2: [[6 4 8 8]
 [2 1 1 4]] 

 sum: [[ 7  5 12 13]
 [ 8  9  5  6]]


In [31]:
#Ex5
import numpy as np
matrix=np.random.randint(0,9,size=(3,3))
print(matrix)
for i in matrix:
  print(np.mean(i))

[[5 3 3]
 [5 1 3]
 [7 3 7]]
3.6666666666666665
3.0
5.666666666666667
